#!/usr/bin/env bash

set -e

PACKAGE=linux

. scripts/env.sh

cd_package

make -j8 -C $TOP/linux ARCH=arm64 O=$PWD defconfig dtbs zImage modules
make -C $TOP/linux ARCH=arm64 O=$PWD INSTALL_MOD_PATH=$SYSROOT modules_install

package_success
