#!/usr/bin/env bash

set -e

PACKAGE=wayland

. scripts/env.sh

cd_package

run_autogen \
--disable-documentation \
--with-host-scanner \
--disable-libraries \
--disable-dtd-validation

run_make
run_make install

package_success
