#!/usr/bin/env bash

set -e

PACKAGE=mesa

. scripts/env.sh

cd_package

run_autogen \
    --with-gallium-drivers=nouveau,swrast,tegra \
    --with-dri-drivers= \
    --with-platforms=x11,drm \
    --with-vulkan-drivers= \
    --with-vulkan-drivers= \
    --enable-texture-float \
    --enable-gallium-osmesa \
    --enable-xa \
    --enable-nine \
    --disable-xvmc \
    --enable-vdpau \
    --enable-omx-bellagio \
    --enable-glx-tls \
    --enable-libglvnd \
    --disable-libunwind

run_make
run_make install

package_success
