#!/usr/bin/env bash

set -e

PACKAGE=linux

. scripts/env.sh

cd_package

sudo make -j$NPROC -C $TOP/linux ARCH=arm64 O=$PWD CROSS_COMPILE=$CROSS_COMPILE defconfig dtbs zImage modules
sudo make -C $TOP/linux ARCH=arm64 O=$PWD CROSS_COMPILE=$CROSS_COMPILE INSTALL_MOD_PATH=$SYSROOT modules_install

package_success
