#!/usr/bin/env bash

set -e

. scripts/env.sh

# Run a command into the chrooted target FS using qemu and proot
run_in_qemu()
{
    PROOT_NO_SECCOMP=1 proot -0 -r $SYSROOT -q $TOP/out/host/qemu/qemu-$ARCH-static -b /etc/resolv.conf -b /etc/mtab -b /proc -b /sys $*
}

if [ ! -e $SYSROOT ]; then
    error "Directory $SYSROOT does not exist. Run ./scripts/download-rootfs to download a fresh image."
    exit 1
fi

status "Setting current user as owner of target FS..."
sudo chown -R $USER $SYSROOT/*
######## ROOTFS OWNED BY USER

. scripts/distro/prepare-$DISTRO

mkdir -p $SYSROOT/$NV_PREFIX
mkdir -p $SYSROOT/boot
mkdir -p $SYSROOT/lib/modules
mkdir -p $SYSROOT/lib/firmware

#status "Adding environment to /etc/profile.d/nouveau.sh"
#cat <<EOF |tee $SYSROOT/etc/profile.d/nouveau.sh >/dev/null
#export PATH="$NV_PREFIX/bin:\$PATH"
#export PKG_CONFIG_PATH="$NV_PREFIX/lib/pkgconfig:\$PKG_CONFIG_PATH"
#EOF

#chmod u+x $SYSROOT/etc/profile.d/nouveau.sh

#status "Adding ld.so.conf.d entry for $NV_PREFIX/lib"
#cat <<EOF |tee $SYSROOT/etc/ld.so.conf.d/nouveau.conf >/dev/null
#$NV_PREFIX/lib
#EOF

status "Enabling Xwayland in Weston configuration"
mkdir -p $SYSROOT/etc/xdg/weston
cat <<EOF >$SYSROOT/etc/xdg/weston/weston.ini
[core]
modules=xwayland.so

[xwayland]
path=/opt/nouveau/bin/Xwayland
EOF

######### LIGHTDM
run_in_qemu systemctl enable lightdm
sed -i 's/#keyboard=/keyboard=onboard/' $SYSROOT/etc/lightdm/lightdm-gtk-greeter.conf

# run_in_qemu systemctl enable gdm

# Enable NetworkManager
run_in_qemu systemctl enable NetworkManager
run_in_qemu systemctl enable bluetooth


cp -R $TOP/linux-firmware/nvidia/ $SYSROOT/lib/firmware/


######## ROOTFS OWNED BY ROOT
status "Setting back root as owner of target FS"
status "Setting current user as owner of /boot, /lib/modules and /lib/firmware"
sudo -s -- <<EOF
chown -R root:root $SYSROOT/*
chown -R 1000:1000 $SYSROOT/home/alarm
chown -R $USER $SYSROOT/$NV_PREFIX $SYSROOT/boot $SYSROOT/lib/modules $SYSROOT/lib/firmware
EOF

status "Target FS ready to compile the open graphics stack!"
